### ISSUE TITLE
Is this optical flow trackintg synchronous(like KLT) or asynchronous(like eklt)?

### ISSUE THREAD

**Issue by SharineLee** [tub-rip/event_based_optical_flow#11]

**Comment by SharineLee** [comment]
Is this optical flow trackintg synchronous(like KLT) or asynchronous(like eklt)?

**Comment by shiba24** [comment]
@SharineLee 
It's synchronous in the sense that the flow estimation is for a batch of events, not for every event incrementally.
Apart from frame+event methods such as EKLT, if you look for an asynchronous optical flow estimation method using events only, I would suggest the followings: https://ieeexplore.ieee.org/document/10008035
