### ISSUE TITLE
Does this network output data in.flo format？

### ISSUE THREAD

**Issue by SharineLee** [tub-rip/event_based_optical_flow#13]
Does this network output data in.flo format？If it does, could you upload the Optical flows resualts (in.flo format) of DSEC dataset and MVSEC dataset? 

Cause i want to use the  the Optical flows resualts (in.flo format) directly for my research. Thanks!

**Comment by shiba24** [comment]
@SharineLee The code already saves .npz file. Can you can manually convert npz file to flo file? Do you have any troubles/problems?
